### ISSUE TITLE
Support long tap gesture

### ISSUE THREAD

**Issue by Sunnyyoung** [bufferapp/buffer-ios-image-viewer#13]
Support long tap gesture in order to share or save the image.

**Comment by DreamingInBinary** [comment]
I think for this one we could possibly just show the `UIActivityViewController` - any thoughts you have on this one @ay8s :smile:?

**Comment by ay8s** [comment]
:+1: Sounds good to me to show UIActivityViewController and ensure we include actions to copy, save etc.

**Comment by DreamingInBinary** [comment]
Merge in [here](https://github.com/bufferapp/buffer-ios-image-viewer/commit/60cbfd2638d7e9dac4edd716a7150f110a40b29a) 👍
