### ISSUE TITLE
Fade black background view alpha when dragging to close

### ISSUE THREAD

**Issue by DreamingInBinary** [bufferapp/buffer-ios-image-viewer#14]
As the user drags an image down to close the image viewer, I'm thinking it might be nice to also fade the alpha transparency of the container's background view as well to better educate the user that they're closing out the image.

**Comment by bre7** [comment]
Considering only the drag in the area between the threshold rects ? Or the whole scrollview ? The first solution is trickier when considering the area inside the threshold rects unless you stop the animation when you leave them since it will trigger `dismissUI()`

**Comment by DreamingInBinary** [comment]
We created a custom controller animation insetad, so we can close this one out 👍
