### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#21]
Dependency wise: SDWebImage does support Carthage already but DACircularProgress doesn't :( (there's an open PR about it though: 60)

Use the PR in a custom fork ? Or accept #15 and exclude DACircularProgress ?

**Comment by DreamingInBinary** [comment]
Hmmm that's a good one. I think we proposed #15 because we thought there was an issue with DACircularProgress but it was actually an issue with the content headers for the images we were requesting. @humberaquino do you know of a good way around this? I haven't used Carthage too much 😄 

cc @ay8s

**Comment by humberaquino** [comment]
Thanks @bre7 !!  And good one @DreamingInBinary ! 

PR #15 was a quick solution for an issue we had with DACircularProgress and our image proxy. We ended up fixing the issue with the proxy and after that the download progress worked again as expected so I think that PR should be closed without merging.

To support carthage and still use DACircularProgress we might want to fork DACircularProgress, merge the carthage support there and use it as our dependency. After that it should be easy to add carthage support for the image viewer.

Would love to know your opinion and @ay8s

**Comment by bre7** [comment]
> [...] merge the carthage support there and use it as our dependency

Sadly there hasn't been any activity in DACircularProgress' repo since June 2015 :disappointed: There's an open PR about Carthage support already there (https://github.com/danielamitay/DACircularProgress/pull/60)
