### ISSUE TITLE
Loading long picture leads to gesture conflict

### ISSUE THREAD

**Issue by Sunnyyoung** [bufferapp/buffer-ios-image-viewer#25]
When an long picture loaded, and once you drag up or down will leads to gesture conflict between the `dismiss action` and `scroll action`.

Sample picture URL: `http://ww4.sinaimg.cn/large/af8c19d2gw1f3hzhbs4kfj20j64e5kej.jpg`

**Comment by bre7** [comment]
Not sure if it's a bug, maybe just a design decision from buffer's team. It only happens when the gesture exceeds the threshold and triggers the vc dismissal.

On Twitter for instance, this doesn't happen. **The vc is only dismissed if the image isn't zoomed in.**

**Comment by DreamingInBinary** [comment]
Hmmm - I think we should handle this better. I'll think on this one, though I'm not sure of the best way off the to of my head.
