### ISSUE TITLE
Play Live Photos

### ISSUE THREAD

**Issue by DreamingInBinary** [bufferapp/buffer-ios-image-viewer#26]
Using `PHAssetMediaSubtypePhotoLive` we could play live photos by getting a `PHLivePhoto` object using `PHImageManager` and then put it inside of a `PHLivePhotoView`.

This is only available in iOS 9.1 and greater so there would need to be a version check.

**Comment by bre7** [comment]
Auto-play ? Since single tap dismisses the view controller. Or use 3D-Touch, if available ?

**Comment by DreamingInBinary** [comment]
Closed [here](https://github.com/bufferapp/buffer-ios-image-viewer/pull/73)
