### ISSUE TITLE
Done button is invisible

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#29]
Using CocoaPods and default settings.

The button is there (verified by debugging and tapping the area) but not visible.
Possible causes:
- Image not loaded from bundle
- Image is the same color as the background

Almost certain it's due to the image not being loaded from the bundle.

Test1:
```swift
presentViewController(imageVC, animated: true) {
    for v in imageVC.view.subviews {
        if let v = v as? UIButton {
            v.backgroundColor = .whiteColor()
            v.setImage(UIImage(named: "closeIcon"), forState:.Normal)
        }
    }
}
```
White square appears at the top-left corner.

Test2:
```swift
presentViewController(imageVC, animated: true) {
    for v in imageVC.view.subviews {
        if let v = v as? UIButton {
            Log.debug(v.imageForState(.Normal))
        }
    }
}
```
Returns nil

**Comment by DreamingInBinary** [comment]
Hey hey @bre7 - do you have a test project I could look at? Happy to take a peek 👍 Also, and I'm sure you probably saw this - but if you use the initializer for 3d touch it'll hide it by default

**Comment by bre7** [comment]
Hi @DreamingInBinary - I've been trying to find out the cause but no luck 😢 Reveal shows the button frame but the UIImage isn't loaded. I've modified your demo also to use CP instead of the local copy and the image is shown but not on the new test project I've created (sent you an invite btw)

**Comment by DreamingInBinary** [comment]
Awesome @bre7 - I'll take a look!

**Comment by bre7** [comment]
It's due to how the image is loaded in the pod bundle. I remembered seeing the same bug in TSMEssages (https://github.com/KrauseFx/TSMessages/pull/218/files)
