### ISSUE TITLE
Set index of image viewer

### ISSUE THREAD

**Issue by Gman9855** [bufferapp/buffer-ios-image-viewer#39]
I have a page view controller of 6 images.  When i tap the third image, for example, I'd like the image viewer to show the third image when it loads, instead of the first.

**Comment by Gman9855** [comment]
#40

**Comment by ay8s** [comment]
Added into new branch here... https://github.com/bufferapp/buffer-ios-image-viewer/tree/task/pinremoteimage-plus-animated-gif-support
