### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [bufferapp/buffer-ios-image-viewer#42]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like buffer-ios-image-viewer, deleted the software history during the transition to open-source.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask buffer-ios-image-viewer developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
hi @humberaquino, do you have any comments?

**Comment by ay8s** [comment]
Thanks for the comment @gustavopinto. 

1. We ported most of the code from internally within the Buffer iOS app which meant we lost most of the history. We could've exported it with the history but wanted to get it out leaner. :) 
2. Not had any issues as it's very rare we need to look back at previous history after implementing this project ourselves internally.
3. Not aware of any issues, could totally be wrong.
4. Image Viewer is pretty small so its probably not too much of an issue in terms of this project. But others I'm sure it would become a problem.

**Comment by gustavopinto** [comment]
Hi @ay8s, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
