### ISSUE TITLE
Progressive JPEGs support

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#48]
~~This feature would replace the progress indicator. Not sure if it's working on SDWebImage~~:
```
https://github.com/rs/SDWebImage/issues/1164
https://github.com/rs/SDWebImage/issues/1671
```

Update: SDWebImage was removed in favor of PINRemoteImage. Continue reading --->

**Comment by DreamingInBinary** [comment]
Good one @bre7 - we're looking to replace SDWebImage with an out of the box solution to get rid of the dependency or either replace it with PINRemoteImage 😄

**Comment by bre7** [comment]
Nice. I replaced it with PINR in a custom fork since I was already using it in an app.

**Comment by DreamingInBinary** [comment]
Awesome - how are things looking with it? Would love to gain insight on your experience with it and see how things went. PINRemoteImage would be great for us since we already use ASDK all throughout Buffer.

**Comment by bre7** [comment]
PINRI is great: deals with caching (it's a separate lib for now, PINCache, I think there were plans to decouple the dependency), adds easy-to-use categories for several UI components, supports GIF/WebP/PJPEG, etc. That's why I submited #35, to allow each dev to use SDWI or any other image fetching library, though it's easier said than done. I think I managed to use it with my swift-only fork.


I've been wanting to try ASDK for the past year or so 😢

**Comment by ay8s** [comment]
Thanks for adding this one @bre7. We have been working on switching out SDWebImage for PINRemoteImage within the Buffer project so will have this one done shortly within the Image Viewer. 👍

**Comment by bre7** [comment]
Awesome !

**Comment by ay8s** [comment]
PINRemoteImage branch is over at https://github.com/bufferapp/buffer-ios-image-viewer/tree/task/pinremoteimage-plus-animated-gif-support will be trying this out a bit before merging.

**Comment by bre7** [comment]
👍 I'll give it a try this weekend. I've used PINRI with progressive JPEGs before and it has always worked flawlessly.

**Comment by bre7** [comment]
Notes:

* If the user chooses to use `setPin_updateWithProgress:YES' (there's no API in the image viewer for this) then the progress view (DACircularProgressView) shouldn't be created.

**Comment by DreamingInBinary** [comment]
Closing this one down as we've got PINRemoteImage in (merge also added gif support). We'll need to think about that `setPin_updateWithProgress:` scenario @bre7 mentioned as well 👍

**Comment by bre7** [comment]
Bump

Just a reminder, since this functionality should also ignore the new "URL Backloading" feature.

**Comment by DreamingInBinary** [comment]
Hey @bre7 👋 - are you using a custom fork that uses `updateWithProgress` out of curiosity? Wondering if that should be something that API consumers can tweak with the image viewer (right now it's hardcoded not to). If it was, then we'd need to branch the logic as you mentioned if it's on with the progress indicator.

**Comment by bre7** [comment]
Hey Jordan, right now I'm using it out of the box but was planning on adding `updateWithProgress`. Also, am I not getting the point of or is backloading almost the same as PINRemoteImage's `placeholder` ?

**Comment by DreamingInBinary** [comment]
Heya @bre7 sorry I missed this notification - you're right that they server almost the same exact purpose. The main reason is we might not always use PINRemoteImage and wanted all the control over the process. 

Enabling progress does need better support, for a few different reasons progressive image loading isn't being used in Buffer which is the main reason why I haven't messed with it here. But in this library I think it makes sense to include. Will reopen this issue to revisit 👍
