### ISSUE TITLE
Improve close button's visibility

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#49]
Similar to Twitter. Simple way to improve visibility for the white button.
Linear gradient example: #95000000 -> #00ffffff

**Comment by DreamingInBinary** [comment]
Interesting idea @bre7 - would you happen to have a screenshot of the effect? One thing we'd need to think about is paging between multiple images and toggling the gradient.

**Comment by bre7** [comment]
I'll post it later, Android screen cap but the idea is pretty much the same: Full width container for the close button, using #95000000 -> #00ffffff as the background gradient.

**Comment by bre7** [comment]
Screenshots (using a mostly-white photo):

![android_gradient](https://cloud.githubusercontent.com/assets/3183848/24771534/5969215c-1ae4-11e7-9657-2fcc318402f2.jpg)    ![android_no_gradient](https://cloud.githubusercontent.com/assets/3183848/24771535/596d3990-1ae4-11e7-8c04-8c69ca7bc389.jpg)

Left to right: with gradient, without gradient.
