### ISSUE TITLE
Move FLAnimatedImage support to subspec

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#54]
Adding a mirror subspec for PINRemoteImage/Core instead of PINRemoteImage would be useful imo when GIF support isn't required (which results in one less dependency, FLAnimatedImage).
Or maybe the other way around ? Add FLAnimatedImage in a new subspec. Same result, different approach.

`USE_FLANIMATED_IMAGE` is the flag defined by PINRemoteImage to detect whether FLAnimatedImage is available or not.

**Comment by DreamingInBinary** [comment]
Closing as this next merge uses Pinterest's `PINCachedAnimatedImage` and `FLAnimatedImage` will be gone.
