### ISSUE TITLE
Add progress indicator for URL backloading

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#60]
It's hard to tell for a user if an image is being loaded or if the low quality version is all there is.

Possible solutions:
* Show the same circular activity indicator on top of the image
* Use a new type of visual cue (green bar on top of the image, similar to Github?)

Edit: Added GIF
<img src="https://cloud.githubusercontent.com/assets/3183848/24893584/de28adb2-1e5a-11e7-8b1f-09c1595590b5.gif" height="700px">

**Comment by DreamingInBinary** [comment]
Good one @bre7 - @ay8s, got any intuition on this one in terms of UI?

**Comment by DreamingInBinary** [comment]
Just a heads up @bre7 - I don't plan on implementing this one as we won't use it for Buffer. That said, if you implement it in a opt-in fashion I'll be happy to merge it.
