### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by bre7** [bufferapp/buffer-ios-image-viewer#61]
Haven't check every string but I think the only issue is https://github.com/bufferapp/buffer-ios-image-viewer/blob/master/BFRImageViewController/BFRImageContainerViewController.m#L419 (Image loading error)

**Comment by DreamingInBinary** [comment]
Will get this one done when I hope on the next round of fixes, [as we've the groundwork done to support it](https://github.com/bufferapp/buffer-ios-image-viewer/blob/master/BFRImageViewController/BFRImageViewerLocalizations.h) 👍
