### ISSUE TITLE
Swift Compiler Warnings

### ISSUE THREAD

**Issue by coreywiley** [bufferapp/buffer-ios-image-viewer#64]
iOS 10.3
Xcode 8.3.3
Swift 3.1

Getting some Swift Compiler warnings and a Semantic Issue with DACircularProgress :)

![screen shot 2017-07-14 at 5 26 33 pm](https://user-images.githubusercontent.com/10385015/28233062-df12164c-68b9-11e7-913b-9a5f878db565.png)

![screen shot 2017-07-14 at 5 31 24 pm](https://user-images.githubusercontent.com/10385015/28233134-4d563764-68ba-11e7-9808-5c0d345968e7.png)

**Comment by yarodevuci** [comment]
+ 1

**Comment by DreamingInBinary** [comment]
This should be fixed.
