### ISSUE TITLE
Call back after BFRBackLoadedImageSource downloads the hiResURL

### ISSUE THREAD

**Issue by DineshBhandari** [bufferapp/buffer-ios-image-viewer#66]
I need to save hiResURL image after it is downloaded to device gallery, but  currently i am unable to get the call back after  BFRBackLoadedImageSource downloads the hiResURL image.

**Comment by DreamingInBinary** [comment]
[Done](https://github.com/bufferapp/buffer-ios-image-viewer/pull/69)
