### ISSUE TITLE
How to get the image from BFRImageViewController ?

### ISSUE THREAD

**Issue by bhoomesh950** [bufferapp/buffer-ios-image-viewer#71]
BFRImageViewController *imageVC = [[BFRImageViewController alloc] 
       initWithImageSource:@[[NSURL URLWithString:@"imageURL"]]];
       [self presentViewController:imageVC animated:YES completion:nil];

i want to store downloaded image please help me how can i do that ?

**Comment by DreamingInBinary** [comment]
Hey there @bhoomesh950 - can you just use the activity controller? Once the image is downloaded, you could just long press it and save it from there.

**Comment by DreamingInBinary** [comment]
Closing this one down.
