### ISSUE TITLE
Expose dismiss / dismissWithoutCustomAnimation as public?

### ISSUE THREAD

**Issue by danielgindi** [bufferapp/buffer-ios-image-viewer#74]
This framework is beautiful!

I've found a few missing things, like exposing the dismiss methods, and disabling dismiss methods - like disable dismiss from tap or from drag.

Are PRs accepted here?

**Comment by DreamingInBinary** [comment]
[Done](https://github.com/bufferapp/buffer-ios-image-viewer/pull/75)
