### ISSUE TITLE
Custom presentation transition doesn't animate as intended

### ISSUE THREAD

**Issue by akaralar** [bufferapp/buffer-ios-image-viewer#81]
I'm trying to implement custom transition as it's mentioned on the readme, where `imageView` passed to the function is an imageView from a table view cell:

```
    private func showImageViewer(for imageView: UIImageView) {
        guard let image = imageView.image else { return }
        imageAnimator.animatedImageContainer = imageView
        imageAnimator.animatedImage = image
        let frame = view.convert(imageView.bounds, from: imageView)

        imageAnimator.imageOriginFrame = frame
        imageAnimator.desiredContentMode = imageView.contentMode

        let imageVC = BFRImageViewController(imageSource: [image])
        imageVC!.transitioningDelegate = imageAnimator

        present(imageVC!, animated: true, completion: nil)
    }
```
The dismiss animation looks and works as intended, but the entrance to the animation looks off. Any idea why that might be happening? I recorded 2 gifs to illustrate the problem.

Content mode is set to aspect fit. I put logs in the library and the frames are calculated correctly. I'm at a loss why this is happening.

![bug1](https://user-images.githubusercontent.com/309655/48897224-8f184580-ee5a-11e8-86cc-e922c67d461c.gif)
![bug2](https://user-images.githubusercontent.com/309655/48897226-8f184580-ee5a-11e8-9f7f-6285be4aeff3.gif)

**Comment by DreamingInBinary** [comment]
Try changing this `let frame = view.convert(imageView.bounds, from: imageView)` to this `let frame = view.convert(imageView.bounds, to: nil)` and let me know if that works.

**Comment by akaralar** [comment]
Thanks for the suggestion but I can't reproduce the issue above again. I wonder whether it was related to the image itself. I'll reopen if this happens again and your solution doesn't fix it. Thanks for taking the time!
