### ISSUE TITLE
Lock dependency 

### ISSUE THREAD

**Issue by iKorich** [bufferapp/buffer-ios-image-viewer#82]
Hi,

please, do not use beta versions of dependence libs.

--
Thanks

**Comment by elbutchma** [comment]
+1

**Comment by DreamingInBinary** [comment]
Hey there folks - I'll see what we can do here soon. For reasons beyond this comment, we've had to use that beta version but we should be able to get around it now 👍

**Comment by ay8s** [comment]
We're no longer using the beta version of PINRemoteImage now it's available :)
