### ISSUE TITLE
New PINRemoteImage pod breaks the framework

### ISSUE THREAD

**Issue by Necrocter** [bufferapp/buffer-ios-image-viewer#86]
The last change in the Podfile breaks the framework.

´´´
pod 'PINRemoteImage', '~> 3.0.0-beta.14'
´´´

Because it seems it doesn't use FLAnimatedImage anymore.

**Comment by DreamingInBinary** [comment]
@Necrocter try deleting your `Podfile.lock` file and running `pod install --repo-update` and let me know if that works.

`FLAnimatedImage` indeed should not be used anymore, as the goal of the last release is to use Pinterest's `PINAnimatedImageView` to replace it and reduce the library dependency graph.

**Comment by lucianocn** [comment]
@Necrocter your app should target iOS >= 11.0
