### ISSUE TITLE
SDWebImage dependency problem

### ISSUE THREAD

**Issue by Necrocter** [bufferapp/buffer-ios-image-viewer#91]
I just updated my SDWebImage dependency to the latest one and but it's not compatible with this library because the parameters from one function changed:

BFRImageContainerViewController line 345

[manager downloadImageWithURL:url options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) 

The error is this one:

No visible @interface for 'SDWebImageManager' declares the selector 'downloadImageWithURL:options:progress:completed:'

I think this is the solution:
https://github.com/SDWebImage/SDWebImage/blob/master/Docs/SDWebImage-4.0-Migration-guide.md

**Comment by DreamingInBinary** [comment]
That's odd, `SDWebImage` is not a dependency in this library, `PINRemoteImage` is which is where that method signature is from. It sounds like it's clashing in your case.

**Comment by Necrocter** [comment]
Yeah you are right the odd thing is that my Podfile has this

pod 'BFRImageViewer'

My Podfile.lock has this:
 - BFRImageViewer (1.0.21):
    - DACircularProgress
    - SDWebImage

And the files doesn't correspond to what it is in repository o_O

**Comment by Necrocter** [comment]
Ok, something weird about the PINRemote dependency happened. Thx for the comment.

**Comment by DreamingInBinary** [comment]
Ah yeah, might've just required another `pod install`, I think we used to have that as a dependency but it was only for the progress indicator, which I ended up rolling myself to take it out.
