### ISSUE TITLE
Photo Single Tap closes viewer

### ISSUE THREAD

**Issue by jhmacdon** [bufferapp/buffer-ios-image-viewer#93]
After some investigation, it appears this is the culprit:

https://github.com/bufferapp/buffer-ios-image-viewer/blob/bff269aabb141fbd7d20d7bbc0547e7a0464769d/BFRImageViewController/BFRImageContainerViewController.m#L538-L540

Is dismissing the intended functionality? It looks like a single tap should cause the ui to be hidden (the close button, share button, etc) rather than dismissing the entire VC which is what happens here.

**Comment by DreamingInBinary** [comment]
Hey there @jhmacdon -

This is bad naming on my part. We used to have this ability but took it out some time ago as most of the time, users in Buffer just want to close the image when they tap anywhere. That method should really be called something like `dimissViewController` - I'm making that change here soon.
